<?php

/**
 * Implements hook_vscc_skin_info().
 */
function wwm_vscc_skins_vscc_skin_info() {
  return array(
    'wwm_icons' => array(
      'name' => t('WWM icons'),
    )
  );
}

/**
 * Implements hook_theme().
 */
function wwm_vscc_skins_theme($existing, $type, $theme, $path) {
  return array(
    'vscc_element_wwm_icons' => array(
      'variables' => array('element' => NULL, 'vss_id' => NULL, 'view' => NULL, 'settings' => array(), 'location' => NULL, 'rows' => array()),
    ),
  );
}

/**
 * Theme function pointing to images.
 *
 * Images may be kept anywhere. In this example they're in a
 * subdirectory of the wwm_vscc_skins module.
 * 
 * Icons were created by Dave Gandy from Flaticon.com: https://www.flaticon.com/packs/font-awesome
 *
 * Copy the function below to your theme's template.php file, replacing "theme_vscc_element_wwm_icons" with "[THEMENAME]_vscc_element_wwm_icons"
 */

// function theme_vscc_element_wwm_icons($vars) {
//   $image_vars = array(
//     'path' => drupal_get_path('module', 'wwm_vscc_skins') . '/images/vscc/wwm_' . $vars['element'] . '.svg',
//     'alt' => t($vars['element']),
//     'title' => t($vars['element']),
//   );
//   return theme('image', $image_vars);
// }
